// Table de correspondance EXPLICITE question LPM -> fiche(s), construite par
// generation (chaque question est issue de ses fiches). Une question peut etre
// reliee a plusieurs fiches. Editer ici pour corriger un lien.

export const LPM_QCARD_MAP: Record<string, string[]> = {
  "q-lpm-base-art22-volet-cyber": ["lpm-art22-volet-cyber"],
  "q-lpm-base-articles-code-defense": ["lpm-code-defense"],
  "q-lpm-base-creation-2006": ["lpm-saiv-dispositif"],
  "q-lpm-base-l1332-1-cooperation": ["lpm-code-defense"],
  "q-lpm-base-l1332-6-1-modif-2015": ["lpm-art22-volet-cyber"],
  "q-lpm-base-menaces-couvertes": ["lpm-saiv-dispositif"],
  "q-lpm-base-pilote-sgdsn": ["lpm-saiv-dispositif"],
  "q-lpm-cadre-dr-perimetres": ["lpm-dr-articulation"],
  "q-lpm-cadre-loi-resilience": ["lpm-restructuration-cer"],
  "q-lpm-cadre-nis2-ee-ei": ["lpm-nis2-articulation"],
  "q-lpm-oiv-confidentialite-listes": ["lpm-designation-oiv"],
  "q-lpm-oiv-delai-observations": ["lpm-designation-oiv"],
  "q-lpm-oiv-designation-arrete": ["lpm-designation-oiv"],
  "q-lpm-oiv-plans-obligatoires": ["lpm-pso-ppp"],
  "q-lpm-oiv-ppp-approbation": ["lpm-pso-ppp"],
  "q-lpm-oiv-pso-vs-ppp": ["lpm-pso-ppp"],
  "q-lpm-perimetre-12-secteurs": ["lpm-12-secteurs"],
  "q-lpm-perimetre-chiffres": ["lpm-oiv-piv-chiffres"],
  "q-lpm-perimetre-dominantes": ["lpm-12-secteurs"],
  "q-lpm-perimetre-oiv-def": ["lpm-oiv-definition"],
  "q-lpm-perimetre-oiv-securite-frais": ["lpm-oiv-definition"],
  "q-lpm-perimetre-piv-protection": ["lpm-oiv-piv-chiffres"],
  "q-lpm-perimetre-secteur-sante": ["lpm-12-secteurs"],
  "q-lpm-regles-arretes-sectoriels": ["lpm-arretes-sectoriels"],
  "q-lpm-regles-definition-siiv": ["lpm-siiv-definition"],
  "q-lpm-regles-detection-pdis": ["lpm-detection-pdis-correlation"],
  "q-lpm-regles-familles": ["lpm-familles-regles"],
  "q-lpm-regles-homologation-qui": ["lpm-homologation-siiv"],
  "q-lpm-regles-qui-identifie-siiv": ["lpm-siiv-definition"],
  "q-lpm-regles20-acces-distant": ["lpm-r18-acces-distant"],
  "q-lpm-regles20-alertes-anssi": ["lpm-r09-alertes"],
  "q-lpm-regles20-authentification": ["lpm-r12-authentification"],
  "q-lpm-regles20-carto-perimetre": ["lpm-r03-cartographie"],
  "q-lpm-regles20-cloisonnement-filtrage": ["lpm-r16-cloisonnement","lpm-r17-filtrage"],
  "q-lpm-regles20-comptes-admin": ["lpm-r14-comptes-admin"],
  "q-lpm-regles20-crise": ["lpm-r10-crise"],
  "q-lpm-regles20-detection-sondes": ["lpm-r07-detection"],
  "q-lpm-regles20-droits-moindre-privilege": ["lpm-r13-droits-acces"],
  "q-lpm-regles20-homologation-role": ["lpm-r02-homologation"],
  "q-lpm-regles20-identification-comptes": ["lpm-r11-identification"],
  "q-lpm-regles20-incidents-declaration": ["lpm-r08-incidents"],
  "q-lpm-regles20-indicateurs": ["lpm-r20-indicateurs"],
  "q-lpm-regles20-installation-durcissement": ["lpm-r19-installation"],
  "q-lpm-regles20-journal-correlation": ["lpm-r05-journalisation","lpm-r06-correlation"],
  "q-lpm-regles20-mcs-contenu": ["lpm-r04-mcs"],
  "q-lpm-regles20-pssi-def": ["lpm-r01-pssi"],
  "q-lpm-regles20-si-admin-dedie": ["lpm-r15-si-admin"],
  "q-lpm-siiv-detection-territoire": ["lpm-detection-territoire"],
  "q-lpm-siiv-l13326-1-autorite": ["lpm-l13326-1-regles"],
  "q-lpm-siiv-l13326-1-frais": ["lpm-l13326-1-regles"],
  "q-lpm-siiv-l13326-2-incidents": ["lpm-l13326-2-incidents"],
  "q-lpm-siiv-l13326-3-controles": ["lpm-l13326-3-controles"],
  "q-lpm-siiv-l13327-sanction": ["lpm-l13327-sanctions"],

  // Renforcement du QCM (2026-06-12) : 35 questions supplementaires.
  "q-lpm-base-operateurs-publics-prives": ["lpm-saiv-dispositif", "lpm-code-defense"],
  "q-lpm-base-origine-dispositif": ["lpm-saiv-dispositif"],
  "q-lpm-cadre-articulation-statut": ["lpm-nis2-articulation"],
  "q-lpm-cadre-socle-reference": ["lpm-restructuration-cer"],
  "q-lpm-oiv-etapes-designation": ["lpm-designation-oiv"],
  "q-lpm-oiv-notification-autorite": ["lpm-designation-oiv"],
  "q-lpm-oiv-ppp-autorite-defense": ["lpm-pso-ppp"],
  "q-lpm-perimetre-criteres-secteur": ["lpm-12-secteurs"],
  "q-lpm-perimetre-oiv-deux-conditions": ["lpm-oiv-definition"],
  "q-lpm-perimetre-texte-liste-secteurs": ["lpm-12-secteurs"],
  "q-lpm-regles-annexe-20": ["lpm-arretes-sectoriels"],
  "q-lpm-regles-calendrier-arretes": ["lpm-arretes-sectoriels"],
  "q-lpm-regles-homogeneite": ["lpm-arretes-sectoriels"],
  "q-lpm-regles-pdis-base-legale": ["lpm-detection-pdis-correlation"],
  "q-lpm-regles-perimetre-application": ["lpm-siiv-definition"],
  "q-lpm-regles20-admin-operations": ["lpm-r14-comptes-admin"],
  "q-lpm-regles20-alertes-permanence": ["lpm-r09-alertes"],
  "q-lpm-regles20-carto-destinataire": ["lpm-r03-cartographie"],
  "q-lpm-regles20-cloisonnement-objectif": ["lpm-r16-cloisonnement"],
  "q-lpm-regles20-correlation-finalite": ["lpm-r06-correlation"],
  "q-lpm-regles20-crise-perimetre": ["lpm-r10-crise"],
  "q-lpm-regles20-detection-base": ["lpm-r07-detection"],
  "q-lpm-regles20-filtrage-flux": ["lpm-r17-filtrage"],
  "q-lpm-regles20-homologation-procedure": ["lpm-r02-homologation"],
  "q-lpm-regles20-indicateurs-granularite": ["lpm-r20-indicateurs"],
  "q-lpm-regles20-journal-evenements": ["lpm-r05-journalisation"],
  "q-lpm-regles20-mcs-ressources": ["lpm-r04-mcs"],
  "q-lpm-regles20-processus-automatiques": ["lpm-r11-identification", "lpm-r12-authentification"],
  "q-lpm-regles20-pssi-verbe": ["lpm-r01-pssi"],
  "q-lpm-regles20-reseaux-tiers": ["lpm-r18-acces-distant"],
  "q-lpm-siiv-controles-acteurs": ["lpm-l13326-3-controles"],
  "q-lpm-siiv-incidents-perimetre": ["lpm-l13326-2-incidents"],
  "q-lpm-siiv-mise-en-demeure": ["lpm-l13327-sanctions"],
  "q-lpm-siiv-mise-en-oeuvre-operationnelle": ["lpm-l13326-1-regles"],
  "q-lpm-siiv-personnes-morales": ["lpm-l13327-sanctions"],
};
